initial commit for median value calculation via R-ArcGIS bridge blog pos
merit-network/merit-network.github.io pull request #24
Opened 2021-02-01 15:50 UTC by merit-amystuyv

initial commit for median value calculation via R-ArcGIS bridge blog post - please review and let me know if I can clarify anything or make any changes

2021-02-01 17:55 UTC, merit-mthompson commented
Not covered in the directions but for the images we're embedding in this repo we want to resize them a bit so they're not so large.

Here's the same image shrunken from ~5MB to ~256K; can we update/replace?

![nathan-dumlao-qq9XjVZe4Lk-unsplash](https://user-images.githubusercontent.com/57911231/106497978-b92f0e80-648c-11eb-9507-741d503f93a4.jpg)

2021-02-01 17:58 UTC, merit-amystuyv commented
no problem, just updated the image file

2021-02-01 17:59 UTC, merit-mthompson requested changes
Looks awesome Amy, nice work! My only suggestion is the date on the post, otherwise it looks perfect.

2021-02-01 17:59 UTC, merit-mthompson commented on content/blog/summarize_within_median_r_arcgis/index.md
> +date: "2020-01-29T10:50:00Z"
Think we want the year to be 2021

```suggestion
date: "2021-01-29T10:50:00Z"
```

2021-02-01 18:58 UTC, merit-mthompson approved these changes

2021-02-01 18:59 UTC, merit-mthompson commented
Looks good to me! Adding others from PSWD as reviewers for the final go-ahead.

2021-02-01 22:16 UTC, merit-rluk approved these changes
Looks great, Amy! I'm going to comment on a few typos but overall I'd say it's good to go.

2021-02-01 22:18 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +_If you've ever longed for 'median' as an option in the dropdown list of Esri's 'Summarize Within' tool when working with non-normally distributed data, long no more! Use this script and the R-ArcGIS
```suggestion
_If you've ever longed for 'median' as an option in the dropdown list of Esri's 'Summarize Within' tool when working with non-normally distributed data, long no more! Use this script and the R-ArcGIS Bridge to fulfill your non-parametric function needs._
```

2021-02-01 22:20 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +There is no question that this data does not satisfy the requirements of normally distributed data, meaning we should ***not*** use a parametric test (e.g. `mean`) to analyze the data. Using the `mea
```suggestion
There is no question that this data does not satisfy the requirements of normally distributed data, meaning we should ***not*** use a parametric test (e.g. `mean`) to analyze the data. Using the `mean` function when aggregating these values up to the census block level would artificially push your average towards those outliers, misrepresenting what the 'average' person in that census block is really experiencing. When the purpose of this analysis is to provide data-driven insight into where new broadband infrastructure investments should be made, pushing the metric towards those high outliers is absolutely unacceptable. Fortunately, the median value of your data provides one option to better represent the true middle ground of what users on the ground are experiencing. 
```

2021-02-01 22:21 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +This particular project has many components and is largely working in ArcGIS Pro's model builder with some deeper statistics and figure generation happening in RStudio. Our goal is to have cohesion b
```suggestion
This particular project has many components and is largely working in ArcGIS Pro's model builder with some deeper statistics and figure generation happening in RStudio. Our goal is to have cohesion between these two programs, so we did not want a workflow that required us to run some analysis in ArcGIS Pro, leave this program and open up RStudio to run a custom-made script, and then go back into ArcGIS Pro to run the rest of the model. Luckily, Esri's R-ArcGIS Bridge allows us to create the custom tool you'll see below and then import that into the ArcGIS Pro interface whenever we want to calculate the median download and upload speeds for each census block in our study area.  
```

2021-02-01 22:21 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +Now we define the input and outputer parameters you want the user to provide via the tool interface in ArcGIS Pro:
```suggestion
Now we define the input and output parameters you want the user to provide via the tool interface in ArcGIS Pro:
```

2021-02-01 22:22 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +  coord_system <- in_params[(5)] #user chooses Point or Polygon from dropdown for the coordinate system they wnat to use
```suggestion
  coord_system <- in_params[(5)] #user chooses Point or Polygon from dropdown for the coordinate system they want to use
```

2021-02-01 22:23 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +  #count total amount of points within each polygoj based on ID supplied by user
```suggestion
  #count total amount of points within each polygon based on ID supplied by user
```

2021-02-01 22:24 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +That's all the code! If you want to test this in RStudio before bringing it into ArcGIS Pro, simply comment out the initial function defintion and parameter defintions, define the parametrs as variab
```suggestion
That's all the code! If you want to test this in RStudio before bringing it into ArcGIS Pro, simply comment out the initial function definition and parameter definitions, define the parameters as variables with the same name as the parameter definition, and run the code from there. 
```

2021-02-01 22:24 UTC, merit-rluk commented on content/blog/summarize_within_median_r_arcgis/index.md
> +It is also worth noting that there are other way to deal with non-normally distibuted data, such as removing outliers or transforing your data, that may work better for your specific project. The mos
```suggestion
It is also worth noting that there are other way to deal with non-normally distributed data, such as removing outliers or transforming your data, that may work better for your specific project. The most important rule of thumb is to always use your brain first about what works best for the intended use of that data.
```

2021-02-02 17:45 UTC, merit-dsclair approved these changes

2021-02-02 17:52 UTC, merit-ddennis approved these changes

2021-02-02 19:49 UTC, merit-schelcj requested changes
Need to run through a linter, multiple issues found with the formatting.

2021-02-02 20:11 UTC, merit-mthompson commented
@merit-amystuyv for markdown linting/checking you can use "markdownlint" plugin with VS Code.

Nearly all of the linting-related suggestions are whitespace around headings/paragraphs. The errors you can ignore are those for "single-h1" or "multiple level-one headings" as in the final blog post we want those level-one headings!

Also safe to ignore are ones about heading capitalization and other writing/style-related things.

2021-02-02 20:47 UTC, merit-amystuyv commented
@merit-schelcj formatting issues have been fixed

2021-02-02 21:13 UTC, merit-schelcj approved these changes

2021-02-03 20:11 UTC, merged